### ISSUE TITLE
any way to get absolute timecode from HLS fragments?

### ISSUE THREAD

**Issue by dhassoun** [mangui/flashls#255]
we need a way to determine the absoulte time for a stream. the encoder is injecting timecode in the fragments, is there any way to get this in the library?

in addition if it is a dvr rolling window is there a way to tell the total time since the beginning of the stream?

**Comment by mangui** [comment]
Hi @dhassoun do you know how your encoder is injecting timecode ? 
through a specific PID in your TS fragments ? if it is the case you can retrieve binary metadata through ID3_UPDATED event(https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSEvent.as#L58).
another option is to add some custom tag in your live playlist, you will then be able to retrieve these tags  when FRAGMENT_PLAYING event will be fired (https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSEvent.as#L58 : https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSPlayMetrics.as#L15)

if it is a DVR rolling window, flashls can provide you the total time since the beginning of the playback (https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSMediatime.as#L16) , but not since the beginning of the stream. but if you use timecode or custom tags you should be able to extract the info from there.
cheers,
Mangui

**Comment by turbidwater** [comment]
We're using a live packager app to turn RTMP into HLS. The timecode is in the stream from the encoder in a way that it can be retrieved using onFI. We're also doing some server-side injection of the timestamp as an ID3 Frame with Comment data using the NetStream send method as described here: https://helpx.adobe.com/adobe-media-server/dev/timed-metadata-hls-hds-streams.html

We've tried sending the ID3 frame on an onMetaInfo, onMetaData, and onID3Data message. I've tried adding those callbacks to the HLSNetStream client, but none of them get triggered. Is there a different way we should be looking to receive those ID3 frames?

Do you have any tool you use to check for correct ID3 metadata? We're also entertaining the possibility that the ID3 data is being stripped by the live packager.

**Comment by mangui** [comment]
@turbidwater flashls supports parsing of ID3 tags embedded in MPEG2-TS.
ID3 PID is detected by parsing the PMT (ID3 PID stream type = 0x15)
this seems consistent with the pointer on apple spec found on your link (https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/Introduction/Introduction.html)

please first check that you get this log:
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/demux/TSDemuxer.as#L814

if any ID3 tag is found, then you should be able to retrieve them by listening to ID3_UPDATED event, which is triggered from here (by listening to onID3Data()
https://github.com/mangui/flashls/blob/1695c63ca9a02fa2d056129b21353f759f620189/src/org/mangui/hls/stream/HLSNetStream.as#L86-L95

**Comment by turbidwater** [comment]
Hmm, it is not getting that log. I see these two PID traces, but not the ID3 one:
- DEBUG:TS: selected MP3 PID: 258
- DEBUG:TS: PAT found.PMT PID:256
It turns out that feature for conversion of send() data to HLS ID3 frames is new. I had to upgrade to AMS 5.0.8, but I'm still not seeing the data come through. I may need to try tweaking the configuration.

I'm unsure of how to validate that ID3 data is being added at all. I've been trying to see if VLC will output metadata from HLS, but it won't output it for anything I've thrown at it, including an audio only m3u8 that triggers your ID3 handling. If I play the RTMP stream, the metadata is coming through. 

Do you have any tools that can spit out the metadata sent in an m3u8? I've tried ffprobe and vlc to no avail.

**Comment by turbidwater** [comment]
I've got a little more information here. I created a VOD m3u8 asset and have uploaded a zip of it here: http://code.realeyes.com/nthingvall/id3Sample.zip This clip plays back with flashls OSMF and also in VLC.

We've validated that the ID3 data is coming through by running the stream through the Primetime SDK. We are getting the ID3 data there as ByteArrays mapped to frame types (COMM). Do you have any suggestions of where the disconnect might be?

**Comment by turbidwater** [comment]
Also if you want just a straight up URL, the m3u8 can be played back here: http://code.realeyes.com/nthingvall/id3Sample/cumin4.m3u8

**Comment by dhassoun** [comment]
any ideas on this one? it would be very very helpful

**Comment by mangui** [comment]
i see some ID3 data by analyzing the TS with a binary editor, but those ID3 data are carried on the video PID.
according to https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/HTTP_Live_Streaming_Metadata_Spec.pdf
ID3 is conveyed in a specific PES packet, with stream id 0xbd.
this way of carrying ID3 is not supported ATM. it would require some changes in TSDemuxer, so that in case any PES packet has such kind of stream id, then it should trigger a ID3 PES parsing, instead of an AVC PES one.

**Comment by dhassoun** [comment]
Is this something you could help with even if this is something we have to
pay for?

[ Sent from mobile device - please excuse brevity or typos ]

**Comment by mangui** [comment]
@dhassoun ,PMT is updated several times in your fragments. I am now reparsing any new PMT upon detection of unknown TS packets. you should now be able to receive ID3_UPDATED events.

**Comment by dhassoun** [comment]
@mangui you are me hero! we will give it a shot. thanks

**Comment by mangui** [comment]
@dhassoun any update ?

**Comment by dhassoun** [comment]
should have an update today - we got delayed on testing this and was hoping
to have done yesterday.

On Thu, May 28, 2015 at 12:53 AM, Guillaume du Pontavice <
notifications@github.com> wrote:

> @dhassoun <https://github.com/dhassoun> any update ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mangui/flashls/issues/255#issuecomment-106199772>.
>



-- 

*[ David Hassoun | Principal ]  *[ Adobe Certified Master Instructor ]
[ p. 303.872.0442 | c. 303.359.7466 | f. 303.433.4002 ]
[ RealEyes Media, LLC | www.realeyes.com ]
[ 940 Logan | Denver CO, 80203 ]

**Comment by turbidwater** [comment]
So far things are looking good! I am getting ID3 data, but now I just need to figure out how to parse it into the data we need. I can at least get the first part of the header (ID3) and am working on parsing the rest to get to that tantalizing timecode. I will let you know how it goes! Thank you so much!

**Comment by turbidwater** [comment]
Success! Once you get through the ID3 Headers that are specified in this article (https://helpx.adobe.com/adobe-media-server/dev/timed-metadata-hls-hds-streams.html) the properties of the object are there, separated by a 0 byte between each value. 

this in SSAS: var comment = { language: "eng", data: "myTimestamp" };

can be extracted like this in AS3:
var lang:String = hexBytes.readMultiByte( 3, 'utf-8' );
var separator:int = hexBytes.readByte();
var timestampString:String = hexBytes.readUTFBytes( hexBytes.bytesAvailable );

**Comment by turbidwater** [comment]
Thanks again so much for all your help, @mangui !
