### ISSUE TITLE
Switching level manually take too long + live problem

### ISSUE THREAD

**Issue by seb-legat** [mangui/flashls#257]
Hello,

I use the plugin in a custom OSMF 2.0 player.

I've got an issue when I want to change the quality (level) manually.
The player indicate that it has successfully changed the currentDynamicStreamIndex with the "DynamicStreamEvent.SWITCHING_CHANGE" event.
But the screen is only updated with the requested quality when I receive the event "DisplayObjectEvent.MEDIA_SIZE_CHANGE", which is fired long time after.
The HLS video use 10 seconds segments but it take almost 1 minute to change quality.
I tried to change the buffer length & max buffer length in HLSSettings but without success.
Any idea how to make the quality change faster (without seeking to force the refresh) ?
I use the same methods to control quality with the HDS Akamai plugin, and it works flawlessly.

Other issue : when I pause a HLS live and resume later, the video continue to play from where it stopped, not where it should be on the live, and freeze after a certain time (as if it doesn't load the next segments). With the HDS live, when you pause the stream and resume it, it skip the part of the live corresponding of the pause (like a real live). How can I force the video to go to the real actual time of the live when resuming ?

Thanks by advance,
Sébastien

**Comment by mangui** [comment]
@seb-legat indeed SWITCHING_CHANGE is triggered when fragment with new quality index will be downloaded. if you have a 60 seconds buffer upfront, the actual quality change will happen one minute after.
I will perform some changes soon so that flashls could support instant level switching when switching from auto to manual quality.
stay tuned

regarding your second issue: flashls support live DVR. you can pause/resume a live stream.
in your case , it is not a standard DVR "resume", it is a seek back to live.
this should be handled differently by the player. 
instead of calling hls.stream.resume(), player should call hls.stream.play(null,-1) to seek back to live.
if you are using OSMF, this would require a change here: 
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/traits/HLSPlayTrait.as#L45
cheers,
mangui
when resuming a live stream

**Comment by seb-legat** [comment]
Thank you for your fast answer !
I will reduce the buffer length until you put a new version of this great plugin online ;)
And thanks for the HLSPlayTrait class and the tip for the live.
Have a nice day !
Sébastien

**Comment by mangui** [comment]
related to #282

**Comment by mangui** [comment]
switching should be faster now with latest release
