### ISSUE TITLE
Strobe Media Playback: invalid parameter passed to method

### ISSUE THREAD

**Issue by Marc477** [mangui/flashls#267]
I tried both Strobe Media Playback and Grindplayer with your HLS plugin, it works fine on localhost, but if I put the .swf on another domain, I get this error (invalid parameter passed to method) with  Strobe Media Playback , and nothing is working with Grindplayer.

This is the only thing i change, I know that the files get loaded (network tab) but then it crashes. I know also that it is not a crossdomain.xml issue since i've put that file on my server (it works with video.js).

 I use chrome 42 and windows 7,  Flash 17.0.0.169

I think you can get a similar issue here:http://osmfhls.kutu.ru/  (SMP player only)

![error](https://cloud.githubusercontent.com/assets/7688794/7425064/3fd766fc-ef78-11e4-902b-372a6200b66d.png)

Thank you

**Comment by mangui** [comment]
@Marc477 , it definitely looks like a security issue.
you can refer to http://www.senocular.com/flash/tutorials/contentdomains/#Trust for some explanation about flash security domain.
from security perspective, flashlsOSMF is quite permissive as it allows any parent swf to access its resource : https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/HLSDynamicPlugin.as#L15
so I doubt there should be an issue from there. i would suspect players (Grind and SMP) to be less permissive) but still this needs to be proven.
do you have any debug logs available ? 
Cheers,
Mangui

**Comment by ErlendHammer** [comment]
I get this error message on Chrome (only) It works well on Firefox for me.
The error message "ArgumentError: invalid parameter passed to method" is related to the poster image. If you remove the reference to the poster image the error message disappears entirely (I.e. the problem is fixed).  However it is undesireable not to have a poster image on a video, so I wonder what is wrong with the poster image loading.  

Another person said it was absolute vs. relative reference to the poster image, but for me nothing worked but removing the poster image altogether.

Many thanks,
Erlend

**Comment by ErlendHammer** [comment]
@mangui Any idea about this :-)?

**Comment by mangui** [comment]
flashls OSMF wrapper does not deal with poster image, poster is handled inside the player logic.
so I can't really help. furthermore there is no code snippet / reduced test case highlighting your issue.

**Comment by ErlendHammer** [comment]
Hi again Guillaume my HLS friend :-)

What do you use to create the m3u8 video stream files? (including variants)

I have been using Sorenson Squeeze Desktop 11, however I think they 
produce substandard files.

What is the state of the art encoder/segmenter tools for HLS?

Many thanks,
Erlend Hammer
