### ISSUE TITLE
http://www.flashls.org/latest/examples/flowplayer/index.html Not working on chrome for android

### ISSUE THREAD

**Issue by shacharz** [mangui/flashls#272]
The message is "Flash version is required", but Chrome for android can play hls with video tag. Should need to fallback to html5 flowplayer?

**Comment by mangui** [comment]
@blacktrash might tell you how to setup FlowPlayer to handle both Flash for desktop and html5 for android ?

**Comment by blacktrash** [comment]
Use Flowplayer HTML5 ;-)
With Flowplayer Flash you can try this hack after loading the [ipad plugin](http://flash.flowplayer.org/plugins/javascript/ipad.html):
```js
flowplayer("playerContainer", "/path/to/flowplayer-3.2.18.swf", {
  // player configuration goes here
}).ipad({simulateiDevice: /android/i.test(navigator.userAgent)});
```
But this is lottery because Android's behaviour varies extremely. Before testing make at least sure that your device actually _does_ play HLS in a video tag, and not only claims to do so. Here's a minimal [test page](http://demos.flowplayer.org/videotest/hls.html).

**Comment by shacharz** [comment]
I wish I could use the Flowplayer HTML5 but AFAIK it doesn't play HLS.
Looks like this hack is working :)

**Comment by blacktrash** [comment]
Flowplayer HTML5 version 6 will play HLS in Flash. Fingers crossed it will be out next week. Stay tuned.
