### ISSUE TITLE
Live streaming - handling load/network problems

### ISSUE THREAD

**Issue by osmestad** [mangui/flashls#406]
Hi!

We have used this player for some big live streaming music events for TIDAL, and mostly it work very well, but we had one issue where the player got stuck (and did not toggle down to lower quality), we think this happened when servers had problems delivering content. Unfortunately we are not able to reproduce this behaviour now, but we suspect it was related to bandwidth and/or latency when a lot of users started watching at the same time. For the next live-event we will try to get our CDN-provider to scale up quicker, but we were wondering if there is anything we could do on the client/player side to optimize for this case?
We are for instance considering using hls_startfromlevel: 0 to force a more conservative starting quality level.

At the time we had this issue we were using a Flashls from around v0.4.1.1 (it was built from source so not exactly sure) with Grind Player. I realize quite a lot has changed since that release, and that this scenario is quite hard to set up a test case for, but figured it was worth asking if you had any pointers? :)

Cheers
Øyvind

**Comment by mangui** [comment]
Hi,
a bunch of fixes have been made since v0.4.1.1, refer to https://github.com/mangui/flashls/releases
@ dailymotion we are using the latest release v0.4.3.4 at the moment, to serve VOD and live. we have analytics and it is working ok. no major glitches.
best would be to set up analytics in your player to understand what is going on at large scale.

**Comment by osmestad** [comment]
Thanks, we will try to keep it updated as I see you have made some more fixes after this as well :)
