### ISSUE TITLE
Question about seek

### ISSUE THREAD

**Issue by roychan** [mangui/flashls#472]
Hi,

I have some questions about the seek event in the library. Because the code is rather complex for me, it would be good if I can get some answers directly here. Specifically, I have two questions. 

When we do a seek to a uncached area, will the buffer size reset to 0 immediately?

When we do a seek and then immediately do another seek before seeking event, will the first seek being canceled?

Thanks a lot for your help.

**Comment by aidaima** [comment]
When we do a seek to a uncached area, will the buffer size reset to 0 immediately?
yes, it will flushBuffer which will clean all tags.

When we do a seek and then immediately do another seek before seeking event, will the first seek being canceled?
if we can seek in buffer, it will reset seekPositionReached and re-calucate _seekPositionRequested; otherwise, it will stop fragment loader and seek again.

**Comment by mangui** [comment]
thanks for answering @aidaima 
yes any pending seek request will be canceled if reseeking.

**Comment by roychan** [comment]
Thanks a lot for answering my questions. That's very helpful.
